\input texinfo
@c -*- texinfo -*-

@c %**start of header
@setfilename tcl2cl.info
@documentencoding UTF-8
@settitle Tcl2CL Reference Manual
@c %**end of header

@include version.texi

@copying
Copyright @copyright{} 2023 Raven Hallsby@*

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A
copy of the license is included in the section entitled ``GNU Free
Documentation License''.
@end copying

@titlepage
@title Tcl2CL Reference Manual
@subtitle Tcl/Tk to Common Lisp Transpiler
@author Raven Hallsby

@insertcopying
@end titlepage

@contents

@c *********************************************************************
@node Top
@top Tcl2CL

This document describes Tcl2CL version @value{VERSION}, a transpiler for
Tcl/Tk.  This transpiler will read a Tcl/Tk script and output an
equivalent Common Lisp script.

@menu
* Introduction::                What is Tcl2CL?
* Resources::                   Resources Tcl2CL used for inspiration.
* Contributing::                You can help too!
@end menu

@node Introduction
@chapter Introduction

@cindex purpose
Tcl/Tk is intended to integrate with the Chil project to provide a
Tcl/Tk-compatible interface to Chil.

Tcl2CL will implement a variant of Tcl, potentially with all of Tcl's
features and quirks, such that almost (hopefully all) Tcl programs may
run without changes.  Ideally, this version of Tcl2CL will read in a Tcl
file, parse it, and output an equivalent ANSI Common Lisp program.

When a procedure that cannot be resolved is encountered, the procedure
is output literally, and the user is responsible for correct handling.

@node Resources
@chapter Resources

The @uref{https://www.tcl.tk, Tcl/Tk website} is @emph{the} location to
get information about the language.  In particular, the
@uref{https://www.tcl.tk/man/ Tcl/Tk manual pages} contain the
specifications for various revisions of the language.

@node Contributing
@chapter Contributing
@cindex documentation

Tcl2CL is documented using the Texinfo system.

@menu
* Submitting Patches::          Sharing your work & improvements.
* Writing Documentation::       Improving & Writing documentation.
@end menu

@node Submitting Patches
@section Submitting Patches
When writing documentation, please use gender-neutral wording when
referring to people, such as
@uref{https://en.wikipedia.org/wiki/Singular_they, singular
``they''@comma{} ``their''@comma{} ``them''}, and so forth.

@quotation Heads Up
Please be sure to test your code with multiple Common Lisp
implementations before submitting your changes!  Tcl2CL is written using
ANSI-compliant Common Lisp, so any conforming implementation should
work.  Tcl2CL is currently tested with @uref{https://www.sbcl.org/, SBCL}
and @uref{https://ccl.clozure.com/, CCL}.
@end quotation

@node Writing Documentation
@section Writing Documentation

To render documentation, you must first make sure that you ran both
@command{./bootstrap} and @command{./configure} in your source tree.
After that you can run one of the following commands:

@itemize
@item @samp{make info} to compile the Info manual.
      You can check it with @command{info doc/tcl2cl.info}.
@item @samp{make doc/tcl2cl.info} to compile the Info manual.
      You can check it with @command{info doc/tcl2cl.info}.
@item @samp{make html} to compile the HTML version.
      You can point your browser to the relevant file in the
      @file{doc/tcl2cl.html} directory.
@item @samp{make doc/tcl2cl.html} to compile the HTML version.
      You can point your browser to the relevant file in the
      @file{doc/tcl2cl.html} directory.
@end itemize

@bye

@c Local Variables:
@c ispell-local-dictionary: "american";
@c End:
